### PR TITLE
Skybridge config added

### PR DESCRIPTION
**Pull request by jgfouca**
Still doesn't work because the account directive is not making it
to the slurm submit script.

[BFB]

### CODE REVIEW

**Comment by rljacob** [comment]
Can you add your changes to machines-acme too?

**Comment by rljacob** [comment]
Just in this fork, not in ESMCI/cime.

**Comment by jgfouca** [comment]
What is machines-acme?

**Comment by rljacob** [comment]
ACME-climate/cime/machines-acme is where we're going to put all the ACME-specific machines files.

**Comment by jgfouca** [comment]
@rljacob , done.

**Pull request merged**
