### PR TITLE
Bring in changes for cime to work with ACME

### PR DESCRIPTION
**Pull request by rljacob**
Some changes are needed to cime for it work with ACME.

This branch was prepared using subtree split from within ACME.   The individual commit messages describe changes made for ACME.

ACME-specific
Remove references to cvmix in Makefile.
Remove the -no-opt-dynamic-align option from intel.
Add +mkl to intel and to blues.

While porting cime to ACME, made some updates to cime:
POP2 is now POP
Update code in preview_namelist.
Use CIME version of Decomp.pm.  We had pre-cime version.

### CODE REVIEW

**Comment by rljacob** [comment]
Wait, why does this have 250+ commits and 2 files changed?

**Comment by rljacob** [comment]
The drv tests passed on blues/intel after merging to master.   The git log looks ok.

**Comment by rljacob** [comment]
@gold2718 Any idea why the github summary above thinks this has 250+ commits and 2 files changed?   Before I actually did the merge and it was just a PR, it was correctly summarized as 5 commits and about 8 files changed.  And that's what the log and graph still show.

**Comment by bishtgautam** [comment]
Github is showing 250+ commits maybe because f4e709c had no parent

```
> git log -n 10 --oneline --graph
*   3e42814 Merge branch 'rljacob/merge-from-acme1' (PR #11)
|\  
| *   181cdfd Merge branch 'rljacob/acmemerge-to-cime1' into rljacob/merge-from-acme1
| |\  
|/ /  
| * fe8c483 Enable pop to build with cime
| * 1e69a10 Enable cice to build with cime
| * 232537f More changes to build ACME CAM with cime
| * f4e709c Add cime as top-level directory in ACME
*   b496e53 Merge branch 'jgfouca/skybridge_working' (PR #7)
|\  
| * a8f6ab6 CIME tests now passing on skybridge
|/  
*   4852e71 Merge branch 'jgfouca/skybrige_config_mirror' (PR #6)
|\  
| * 8713307 Add file that I forgot to add in last PR

```

**Comment by rljacob** [comment]
I see.  I guess that's just a feature of a branch brought in from a subtree split?

**Comment by rljacob** [comment]
NOTE:  the merge of this PR was wiped out (on purpose) by a force push to master.  master was restored to state after PR #7

**Pull request merged**
